let db;const v=document.getElementById('view');const nav=[...document.querySelectorAll('nav button')];
function setActive(x){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===x))}
fetch('cards.json').then(r=>r.json()).then(d=>{db=d;home()});
function home(){setActive('home');const total=db.cards.length;const players=[...new Set(db.cards.map(c=>c.player))].length;v.innerHTML=`<div class=hero><h2>Mission Control</h2><p>Premium portfolio tracker.</p></div><div class=grid><div class=metric><span>Cards</span><b>${total}</b></div><div class=metric><span>Players</span><b>${players}</b></div><div class=metric><span>PSA 10</span><b>${db.cards.filter(c=>c.grade==='PSA 10').length}</b></div><div class=metric><span>Crown Jewel</span><b>Lamine</b></div></div><div class=card><span class=tag>Featured</span><h3>Lamine Sapphire Image Variation</h3><p>Our flagship position.</p></div>`}
function collection(){setActive('collection');const groups={};db.cards.forEach(c=>(groups[c.player]??=[]).push(c));v.innerHTML='<h2>Collection</h2>'+Object.entries(groups).map(([p,c])=>`<div class=card><div class=player><div><h3>${p}</h3><small>${c.length} cards</small></div><button class=btn onclick='showPlayer(${JSON.stringify(p)})'>Open</button></div></div>`).join('')}
window.showPlayer=(p)=>{const cards=db.cards.filter(c=>c.player===p);v.innerHTML=`<button class=btn onclick='collection()'>← Back</button><h2>${p}</h2>`+cards.map(c=>`<div class=card><span class=tag>${c.grade}</span><h3>${c.card}</h3><p>${c.details}</p><small>Paid £${c.price||0}</small></div>`).join('')}
function analytics(){setActive('analytics');const total=db.cards.reduce((a,c)=>a+(c.price||0),0);v.innerHTML=`<h2>Analytics</h2><div class=grid><div class=metric><span>Cost Basis</span><b>£${total}</b></div><div class=metric><span>Raw Cards</span><b>${db.cards.filter(c=>c.grade==='Raw').length}</b></div></div><div class=card><h3>Portfolio Mix</h3><p>Lamine • Jude • Flagg • Wemby</p></div>`}
function sniper(){setActive('sniper');v.innerHTML=`<h2>Sniper Board</h2><div class=card><h3>Targets</h3><p>Lamine Sapphire RC — Max £900</p><p>Jude Sapphire RC — Max £350</p><p>Flagg Inception /125 — Max £110</p></div>`}
nav.forEach(b=>b.onclick=()=>({home,collection,analytics,sniper}[b.dataset.view]()));
document.getElementById('searchBtn').onclick=()=>{v.innerHTML=`<h2>Search</h2><input id=s placeholder='Player or card'><div id=r></div>`;s.oninput=()=>{const q=s.value.toLowerCase();r.innerHTML=db.cards.filter(c=>(c.player+c.card).toLowerCase().includes(q)).map(c=>`<div class=card><span class=tag>${c.player}</span><h3>${c.card}</h3><small>${c.grade}</small></div>`).join('')}};